/*
###############################################################
#  Generated by:      Cadence Encounter 13.13-s017_1
#  OS:                Linux x86_64(Host ID microelnsys)
#  Generated on:      Thu Jul 21 20:45:23 2016
#  Design:            P4adder
#  Command:           saveNetlist P4_ADDER_postroute.v
###############################################################
*/
module ND2_95 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_94 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_93 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_92 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_91 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_90 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_89 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_88 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_87 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_86 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_85 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_84 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_83 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_82 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_81 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_80 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_79 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_78 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_77 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_76 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_75 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_74 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_73 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_72 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_71 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_70 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_69 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_68 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_67 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_66 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_65 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_64 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_63 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_62 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_61 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_60 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_59 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_58 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_57 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_56 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_55 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_54 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_53 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_52 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_51 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_50 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_49 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_48 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_47 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_46 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_45 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_44 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_43 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_42 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_41 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_40 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_39 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_38 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_37 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_36 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_35 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_34 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_33 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_32 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_31 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_30 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_29 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_28 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_27 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_26 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_25 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_24 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_23 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_22 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_21 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_20 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_19 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_18 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_17 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_16 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_15 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_14 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_13 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_12 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_11 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_10 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_9 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_8 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_7 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_6 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_5 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_4 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_3 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_2 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module ND2_1 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module IV_7 (
	A, 
	Y);
   input A;
   output Y;

   INV_X1 U1 (.ZN(Y),
	.A(A));
endmodule

module IV_6 (
	A, 
	Y);
   input A;
   output Y;

   INV_X1 U1 (.ZN(Y),
	.A(A));
endmodule

module IV_5 (
	A, 
	Y);
   input A;
   output Y;

   INV_X1 U1 (.ZN(Y),
	.A(A));
endmodule

module IV_4 (
	A, 
	Y);
   input A;
   output Y;

   INV_X1 U1 (.ZN(Y),
	.A(A));
endmodule

module IV_3 (
	A, 
	Y);
   input A;
   output Y;

   INV_X1 U1 (.ZN(Y),
	.A(A));
endmodule

module IV_2 (
	A, 
	Y);
   input A;
   output Y;

   INV_X1 U1 (.ZN(Y),
	.A(A));
endmodule

module IV_1 (
	A, 
	Y);
   input A;
   output Y;

   INV_X1 U1 (.ZN(Y),
	.A(A));
endmodule

module FA_63 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_62 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_61 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_60 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_59 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_58 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_57 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_56 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_55 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_54 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_53 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_52 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_51 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_50 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_49 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_48 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_47 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_46 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_45 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_44 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_43 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_42 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_41 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_40 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_39 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_38 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_37 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_36 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_35 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_34 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_33 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_32 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_31 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_30 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_29 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_28 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_27 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_26 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_25 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_24 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_23 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_22 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_21 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_20 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_19 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_18 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_17 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_16 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_15 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_14 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_13 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_12 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_11 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_10 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_9 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_8 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_7 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_6 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_5 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module FA_4 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_3 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_2 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n1;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n1));
   AOI22_X1 U2 (.ZN(n1),
	.B2(Ci),
	.B1(n3),
	.A2(A),
	.A1(B));
endmodule

module FA_1 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n3),
	.A(Ci));
   XOR2_X1 U4 (.Z(n3),
	.B(B),
	.A(A));
endmodule

module MUX21_GENERIC_N4_7 (
	A, 
	B, 
	SEL, 
	Y);
   input [3:0] A;
   input [3:0] B;
   input SEL;
   output [3:0] Y;

   // Internal wires
   wire SB;
   wire [3:0] Y1;
   wire [3:0] Y2;

   IV_7 UIV (.A(SEL),
	.Y(SB));
   ND2_84 UND1_3 (.A(A[3]),
	.B(SEL),
	.Y(Y1[3]));
   ND2_83 UND2_3 (.A(B[3]),
	.B(SB),
	.Y(Y2[3]));
   ND2_82 UND3_3 (.A(Y1[3]),
	.B(Y2[3]),
	.Y(Y[3]));
   ND2_81 UND1_2 (.A(A[2]),
	.B(SEL),
	.Y(Y1[2]));
   ND2_80 UND2_2 (.A(B[2]),
	.B(SB),
	.Y(Y2[2]));
   ND2_79 UND3_2 (.A(Y1[2]),
	.B(Y2[2]),
	.Y(Y[2]));
   ND2_78 UND1_1 (.A(A[1]),
	.B(SEL),
	.Y(Y1[1]));
   ND2_77 UND2_1 (.A(B[1]),
	.B(SB),
	.Y(Y2[1]));
   ND2_76 UND3_1 (.A(Y1[1]),
	.B(Y2[1]),
	.Y(Y[1]));
   ND2_75 UND1_0 (.A(A[0]),
	.B(SEL),
	.Y(Y1[0]));
   ND2_74 UND2_0 (.A(B[0]),
	.B(SB),
	.Y(Y2[0]));
   ND2_73 UND3_0 (.A(Y1[0]),
	.B(Y2[0]),
	.Y(Y[0]));
endmodule

module MUX21_GENERIC_N4_6 (
	A, 
	B, 
	SEL, 
	Y);
   input [3:0] A;
   input [3:0] B;
   input SEL;
   output [3:0] Y;

   // Internal wires
   wire SB;
   wire [3:0] Y1;
   wire [3:0] Y2;

   IV_6 UIV (.A(SEL),
	.Y(SB));
   ND2_72 UND1_3 (.A(A[3]),
	.B(SEL),
	.Y(Y1[3]));
   ND2_71 UND2_3 (.A(B[3]),
	.B(SB),
	.Y(Y2[3]));
   ND2_70 UND3_3 (.A(Y1[3]),
	.B(Y2[3]),
	.Y(Y[3]));
   ND2_69 UND1_2 (.A(A[2]),
	.B(SEL),
	.Y(Y1[2]));
   ND2_68 UND2_2 (.A(B[2]),
	.B(SB),
	.Y(Y2[2]));
   ND2_67 UND3_2 (.A(Y1[2]),
	.B(Y2[2]),
	.Y(Y[2]));
   ND2_66 UND1_1 (.A(A[1]),
	.B(SEL),
	.Y(Y1[1]));
   ND2_65 UND2_1 (.A(B[1]),
	.B(SB),
	.Y(Y2[1]));
   ND2_64 UND3_1 (.A(Y1[1]),
	.B(Y2[1]),
	.Y(Y[1]));
   ND2_63 UND1_0 (.A(A[0]),
	.B(SEL),
	.Y(Y1[0]));
   ND2_62 UND2_0 (.A(B[0]),
	.B(SB),
	.Y(Y2[0]));
   ND2_61 UND3_0 (.A(Y1[0]),
	.B(Y2[0]),
	.Y(Y[0]));
endmodule

module MUX21_GENERIC_N4_5 (
	A, 
	B, 
	SEL, 
	Y);
   input [3:0] A;
   input [3:0] B;
   input SEL;
   output [3:0] Y;

   // Internal wires
   wire SB;
   wire [3:0] Y1;
   wire [3:0] Y2;

   IV_5 UIV (.A(SEL),
	.Y(SB));
   ND2_60 UND1_3 (.A(A[3]),
	.B(SEL),
	.Y(Y1[3]));
   ND2_59 UND2_3 (.A(B[3]),
	.B(SB),
	.Y(Y2[3]));
   ND2_58 UND3_3 (.A(Y1[3]),
	.B(Y2[3]),
	.Y(Y[3]));
   ND2_57 UND1_2 (.A(A[2]),
	.B(SEL),
	.Y(Y1[2]));
   ND2_56 UND2_2 (.A(B[2]),
	.B(SB),
	.Y(Y2[2]));
   ND2_55 UND3_2 (.A(Y1[2]),
	.B(Y2[2]),
	.Y(Y[2]));
   ND2_54 UND1_1 (.A(A[1]),
	.B(SEL),
	.Y(Y1[1]));
   ND2_53 UND2_1 (.A(B[1]),
	.B(SB),
	.Y(Y2[1]));
   ND2_52 UND3_1 (.A(Y1[1]),
	.B(Y2[1]),
	.Y(Y[1]));
   ND2_51 UND1_0 (.A(A[0]),
	.B(SEL),
	.Y(Y1[0]));
   ND2_50 UND2_0 (.A(B[0]),
	.B(SB),
	.Y(Y2[0]));
   ND2_49 UND3_0 (.A(Y1[0]),
	.B(Y2[0]),
	.Y(Y[0]));
endmodule

module MUX21_GENERIC_N4_4 (
	A, 
	B, 
	SEL, 
	Y);
   input [3:0] A;
   input [3:0] B;
   input SEL;
   output [3:0] Y;

   // Internal wires
   wire SB;
   wire [3:0] Y1;
   wire [3:0] Y2;

   IV_4 UIV (.A(SEL),
	.Y(SB));
   ND2_48 UND1_3 (.A(A[3]),
	.B(SEL),
	.Y(Y1[3]));
   ND2_47 UND2_3 (.A(B[3]),
	.B(SB),
	.Y(Y2[3]));
   ND2_46 UND3_3 (.A(Y1[3]),
	.B(Y2[3]),
	.Y(Y[3]));
   ND2_45 UND1_2 (.A(A[2]),
	.B(SEL),
	.Y(Y1[2]));
   ND2_44 UND2_2 (.A(B[2]),
	.B(SB),
	.Y(Y2[2]));
   ND2_43 UND3_2 (.A(Y1[2]),
	.B(Y2[2]),
	.Y(Y[2]));
   ND2_42 UND1_1 (.A(A[1]),
	.B(SEL),
	.Y(Y1[1]));
   ND2_41 UND2_1 (.A(B[1]),
	.B(SB),
	.Y(Y2[1]));
   ND2_40 UND3_1 (.A(Y1[1]),
	.B(Y2[1]),
	.Y(Y[1]));
   ND2_39 UND1_0 (.A(A[0]),
	.B(SEL),
	.Y(Y1[0]));
   ND2_38 UND2_0 (.A(B[0]),
	.B(SB),
	.Y(Y2[0]));
   ND2_37 UND3_0 (.A(Y1[0]),
	.B(Y2[0]),
	.Y(Y[0]));
endmodule

module MUX21_GENERIC_N4_3 (
	A, 
	B, 
	SEL, 
	Y);
   input [3:0] A;
   input [3:0] B;
   input SEL;
   output [3:0] Y;

   // Internal wires
   wire SB;
   wire [3:0] Y1;
   wire [3:0] Y2;

   IV_3 UIV (.A(SEL),
	.Y(SB));
   ND2_36 UND1_3 (.A(A[3]),
	.B(SEL),
	.Y(Y1[3]));
   ND2_35 UND2_3 (.A(B[3]),
	.B(SB),
	.Y(Y2[3]));
   ND2_34 UND3_3 (.A(Y1[3]),
	.B(Y2[3]),
	.Y(Y[3]));
   ND2_33 UND1_2 (.A(A[2]),
	.B(SEL),
	.Y(Y1[2]));
   ND2_32 UND2_2 (.A(B[2]),
	.B(SB),
	.Y(Y2[2]));
   ND2_31 UND3_2 (.A(Y1[2]),
	.B(Y2[2]),
	.Y(Y[2]));
   ND2_30 UND1_1 (.A(A[1]),
	.B(SEL),
	.Y(Y1[1]));
   ND2_29 UND2_1 (.A(B[1]),
	.B(SB),
	.Y(Y2[1]));
   ND2_28 UND3_1 (.A(Y1[1]),
	.B(Y2[1]),
	.Y(Y[1]));
   ND2_27 UND1_0 (.A(A[0]),
	.B(SEL),
	.Y(Y1[0]));
   ND2_26 UND2_0 (.A(B[0]),
	.B(SB),
	.Y(Y2[0]));
   ND2_25 UND3_0 (.A(Y1[0]),
	.B(Y2[0]),
	.Y(Y[0]));
endmodule

module MUX21_GENERIC_N4_2 (
	A, 
	B, 
	SEL, 
	Y);
   input [3:0] A;
   input [3:0] B;
   input SEL;
   output [3:0] Y;

   // Internal wires
   wire SB;
   wire [3:0] Y1;
   wire [3:0] Y2;

   IV_2 UIV (.A(SEL),
	.Y(SB));
   ND2_24 UND1_3 (.A(A[3]),
	.B(SEL),
	.Y(Y1[3]));
   ND2_23 UND2_3 (.A(B[3]),
	.B(SB),
	.Y(Y2[3]));
   ND2_22 UND3_3 (.A(Y1[3]),
	.B(Y2[3]),
	.Y(Y[3]));
   ND2_21 UND1_2 (.A(A[2]),
	.B(SEL),
	.Y(Y1[2]));
   ND2_20 UND2_2 (.A(B[2]),
	.B(SB),
	.Y(Y2[2]));
   ND2_19 UND3_2 (.A(Y1[2]),
	.B(Y2[2]),
	.Y(Y[2]));
   ND2_18 UND1_1 (.A(A[1]),
	.B(SEL),
	.Y(Y1[1]));
   ND2_17 UND2_1 (.A(B[1]),
	.B(SB),
	.Y(Y2[1]));
   ND2_16 UND3_1 (.A(Y1[1]),
	.B(Y2[1]),
	.Y(Y[1]));
   ND2_15 UND1_0 (.A(A[0]),
	.B(SEL),
	.Y(Y1[0]));
   ND2_14 UND2_0 (.A(B[0]),
	.B(SB),
	.Y(Y2[0]));
   ND2_13 UND3_0 (.A(Y1[0]),
	.B(Y2[0]),
	.Y(Y[0]));
endmodule

module MUX21_GENERIC_N4_1 (
	A, 
	B, 
	SEL, 
	Y);
   input [3:0] A;
   input [3:0] B;
   input SEL;
   output [3:0] Y;

   // Internal wires
   wire SB;
   wire [3:0] Y1;
   wire [3:0] Y2;

   IV_1 UIV (.A(SEL),
	.Y(SB));
   ND2_12 UND1_3 (.A(A[3]),
	.B(SEL),
	.Y(Y1[3]));
   ND2_11 UND2_3 (.A(B[3]),
	.B(SB),
	.Y(Y2[3]));
   ND2_10 UND3_3 (.A(Y1[3]),
	.B(Y2[3]),
	.Y(Y[3]));
   ND2_9 UND1_2 (.A(A[2]),
	.B(SEL),
	.Y(Y1[2]));
   ND2_8 UND2_2 (.A(B[2]),
	.B(SB),
	.Y(Y2[2]));
   ND2_7 UND3_2 (.A(Y1[2]),
	.B(Y2[2]),
	.Y(Y[2]));
   ND2_6 UND1_1 (.A(A[1]),
	.B(SEL),
	.Y(Y1[1]));
   ND2_5 UND2_1 (.A(B[1]),
	.B(SB),
	.Y(Y2[1]));
   ND2_4 UND3_1 (.A(Y1[1]),
	.B(Y2[1]),
	.Y(Y[1]));
   ND2_3 UND1_0 (.A(A[0]),
	.B(SEL),
	.Y(Y1[0]));
   ND2_2 UND2_0 (.A(B[0]),
	.B(SB),
	.Y(Y2[0]));
   ND2_1 UND3_0 (.A(Y1[0]),
	.B(Y2[0]),
	.Y(Y[0]));
endmodule

module RCA_generic_N4_15 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_60 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_59 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_58 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_57 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_14 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_56 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_55 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_54 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_53 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_13 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_52 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_51 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_50 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_49 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_12 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_48 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_47 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_46 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_45 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_11 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_44 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_43 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_42 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_41 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_10 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_40 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_39 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_38 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_37 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_9 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_36 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_35 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_34 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_33 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_8 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_32 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_31 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_30 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_29 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_7 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_28 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_27 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_26 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_25 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_6 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_24 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_23 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_22 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_21 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_5 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_20 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_19 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_18 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_17 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_4 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_16 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_15 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_14 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_13 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_3 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_12 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_11 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_10 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_9 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_2 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_8 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_7 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_6 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_5 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module RCA_generic_N4_1 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_4 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_3 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_2 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_1 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module cs_generic_N4_7 (
	A, 
	B, 
	Ci, 
	S);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;

   RCA_generic_N4_14 UADDER1 (.A(A),
	.B(B),
	.Ci(1'b0),
	.S(S1));
   RCA_generic_N4_13 UADDER2 (.A(A),
	.B(B),
	.Ci(1'b1),
	.S(S2));
   MUX21_GENERIC_N4_7 U1 (.A(S2),
	.B(S1),
	.SEL(Ci),
	.Y(S));
endmodule

module cs_generic_N4_6 (
	A, 
	B, 
	Ci, 
	S);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;

   RCA_generic_N4_12 UADDER1 (.A(A),
	.B(B),
	.Ci(1'b0),
	.S(S1));
   RCA_generic_N4_11 UADDER2 (.A(A),
	.B(B),
	.Ci(1'b1),
	.S(S2));
   MUX21_GENERIC_N4_6 U1 (.A(S2),
	.B(S1),
	.SEL(Ci),
	.Y(S));
endmodule

module cs_generic_N4_5 (
	A, 
	B, 
	Ci, 
	S);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;

   RCA_generic_N4_10 UADDER1 (.A(A),
	.B(B),
	.Ci(1'b0),
	.S(S1));
   RCA_generic_N4_9 UADDER2 (.A(A),
	.B(B),
	.Ci(1'b1),
	.S(S2));
   MUX21_GENERIC_N4_5 U1 (.A(S2),
	.B(S1),
	.SEL(Ci),
	.Y(S));
endmodule

module cs_generic_N4_4 (
	A, 
	B, 
	Ci, 
	S);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;

   RCA_generic_N4_8 UADDER1 (.A(A),
	.B(B),
	.Ci(1'b0),
	.S(S1));
   RCA_generic_N4_7 UADDER2 (.A(A),
	.B(B),
	.Ci(1'b1),
	.S(S2));
   MUX21_GENERIC_N4_4 U1 (.A(S2),
	.B(S1),
	.SEL(Ci),
	.Y(S));
endmodule

module cs_generic_N4_3 (
	A, 
	B, 
	Ci, 
	S);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;

   RCA_generic_N4_6 UADDER1 (.A(A),
	.B(B),
	.Ci(1'b0),
	.S(S1));
   RCA_generic_N4_5 UADDER2 (.A(A),
	.B(B),
	.Ci(1'b1),
	.S(S2));
   MUX21_GENERIC_N4_3 U1 (.A(S2),
	.B(S1),
	.SEL(Ci),
	.Y(S));
endmodule

module cs_generic_N4_2 (
	A, 
	B, 
	Ci, 
	S);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;

   RCA_generic_N4_4 UADDER1 (.A(A),
	.B(B),
	.Ci(1'b0),
	.S(S1));
   RCA_generic_N4_3 UADDER2 (.A(A),
	.B(B),
	.Ci(1'b1),
	.S(S2));
   MUX21_GENERIC_N4_2 U1 (.A(S2),
	.B(S1),
	.SEL(Ci),
	.Y(S));
endmodule

module cs_generic_N4_1 (
	A, 
	B, 
	Ci, 
	S);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;

   RCA_generic_N4_2 UADDER1 (.A(A),
	.B(B),
	.Ci(1'b0),
	.S(S1));
   RCA_generic_N4_1 UADDER2 (.A(A),
	.B(B),
	.Ci(1'b1),
	.S(S2));
   MUX21_GENERIC_N4_1 U1 (.A(S2),
	.B(S1),
	.SEL(Ci),
	.Y(S));
endmodule

module block_pg_26 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_25 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_24 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_23 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_22 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_21 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   AND2_X1 U1 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
   INV_X1 U2 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U3 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
endmodule

module block_pg_20 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_19 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_18 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   AND2_X1 U1 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
   INV_X1 U2 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U3 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
endmodule

module block_pg_17 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   AND2_X1 U1 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
   INV_X1 U2 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U3 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
endmodule

module block_pg_16 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_15 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_14 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_13 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_12 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   AND2_X1 U1 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
   INV_X1 U2 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U3 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
endmodule

module block_pg_11 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_10 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_9 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_8 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_7 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_6 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   AOI21_X1 U1 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   INV_X1 U2 (.ZN(Gij),
	.A(n1));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_5 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   AND2_X1 U1 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
   INV_X1 U2 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U3 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
endmodule

module block_pg_4 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_3 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U3 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
endmodule

module block_pg_2 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   AND2_X1 U1 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
   INV_X1 U2 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U3 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
endmodule

module block_pg_1 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n1;

   AOI21_X1 U1 (.ZN(n1),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
   AND2_X1 U2 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
   INV_X1 U3 (.ZN(Gij),
	.A(n1));
endmodule

module block_g_9 (
	Pik, 
	Gik, 
	Gk1j, 
	Gij);
   input Pik;
   input Gik;
   input Gk1j;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Gk1j),
	.B1(Pik),
	.A(Gik));
endmodule

module block_g_8 (
	Pik, 
	Gik, 
	Gk1j, 
	Gij);
   input Pik;
   input Gik;
   input Gk1j;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Gk1j),
	.B1(Pik),
	.A(Gik));
endmodule

module block_g_7 (
	Pik, 
	Gik, 
	Gk1j, 
	Gij);
   input Pik;
   input Gik;
   input Gk1j;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Gk1j),
	.B1(Pik),
	.A(Gik));
endmodule

module block_g_6 (
	Pik, 
	Gik, 
	Gk1j, 
	Gij);
   input Pik;
   input Gik;
   input Gk1j;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Gk1j),
	.B1(Pik),
	.A(Gik));
endmodule

module block_g_5 (
	Pik, 
	Gik, 
	Gk1j, 
	Gij);
   input Pik;
   input Gik;
   input Gk1j;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Gk1j),
	.B1(Pik),
	.A(Gik));
endmodule

module block_g_4 (
	Pik, 
	Gik, 
	Gk1j, 
	Gij);
   input Pik;
   input Gik;
   input Gk1j;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Gk1j),
	.B1(Pik),
	.A(Gik));
endmodule

module block_g_3 (
	Pik, 
	Gik, 
	Gk1j, 
	Gij);
   input Pik;
   input Gik;
   input Gk1j;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Gk1j),
	.B1(Pik),
	.A(Gik));
endmodule

module block_g_2 (
	Pik, 
	Gik, 
	Gk1j, 
	Gij);
   input Pik;
   input Gik;
   input Gk1j;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Gk1j),
	.B1(Pik),
	.A(Gik));
endmodule

module block_g_1 (
	Pik, 
	Gik, 
	Gk1j, 
	Gij);
   input Pik;
   input Gik;
   input Gk1j;
   output Gij;

   // Internal wires
   wire n1;

   INV_X1 U1 (.ZN(Gij),
	.A(n1));
   AOI21_X1 U2 (.ZN(n1),
	.B2(Gk1j),
	.B1(Pik),
	.A(Gik));
endmodule

module ND2_0 (
	A, 
	B, 
	Y);
   input A;
   input B;
   output Y;

   // Internal wires
   wire N1;

   assign Y = N1 ;

   NAND2_X1 U1 (.ZN(N1),
	.A2(A),
	.A1(B));
endmodule

module IV_0 (
	A, 
	Y);
   input A;
   output Y;

   INV_X1 U1 (.ZN(Y),
	.A(A));
endmodule

module FA_0 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input A;
   input B;
   input Ci;
   output S;
   output Co;

   // Internal wires
   wire n2;
   wire n3;

   XOR2_X1 U3 (.Z(S),
	.B(n2),
	.A(Ci));
   XOR2_X1 U4 (.Z(n2),
	.B(B),
	.A(A));
   INV_X1 U1 (.ZN(Co),
	.A(n3));
   AOI22_X1 U2 (.ZN(n3),
	.B2(Ci),
	.B1(n2),
	.A2(A),
	.A1(B));
endmodule

module MUX21_GENERIC_N4_0 (
	A, 
	B, 
	SEL, 
	Y);
   input [3:0] A;
   input [3:0] B;
   input SEL;
   output [3:0] Y;

   // Internal wires
   wire SB;
   wire [3:0] Y1;
   wire [3:0] Y2;

   IV_0 UIV (.A(SEL),
	.Y(SB));
   ND2_0 UND1_3 (.A(A[3]),
	.B(SEL),
	.Y(Y1[3]));
   ND2_95 UND2_3 (.A(B[3]),
	.B(SB),
	.Y(Y2[3]));
   ND2_94 UND3_3 (.A(Y1[3]),
	.B(Y2[3]),
	.Y(Y[3]));
   ND2_93 UND1_2 (.A(A[2]),
	.B(SEL),
	.Y(Y1[2]));
   ND2_92 UND2_2 (.A(B[2]),
	.B(SB),
	.Y(Y2[2]));
   ND2_91 UND3_2 (.A(Y1[2]),
	.B(Y2[2]),
	.Y(Y[2]));
   ND2_90 UND1_1 (.A(A[1]),
	.B(SEL),
	.Y(Y1[1]));
   ND2_89 UND2_1 (.A(B[1]),
	.B(SB),
	.Y(Y2[1]));
   ND2_88 UND3_1 (.A(Y1[1]),
	.B(Y2[1]),
	.Y(Y[1]));
   ND2_87 UND1_0 (.A(A[0]),
	.B(SEL),
	.Y(Y1[0]));
   ND2_86 UND2_0 (.A(B[0]),
	.B(SB),
	.Y(Y2[0]));
   ND2_85 UND3_0 (.A(Y1[0]),
	.B(Y2[0]),
	.Y(Y[0]));
endmodule

module RCA_generic_N4_0 (
	A, 
	B, 
	Ci, 
	S, 
	Co);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;
   output Co;

   // Internal wires
   wire [3:1] CTMP;

   FA_0 FAI_1 (.A(A[0]),
	.B(B[0]),
	.Ci(Ci),
	.S(S[0]),
	.Co(CTMP[1]));
   FA_63 FAI_2 (.A(A[1]),
	.B(B[1]),
	.Ci(CTMP[1]),
	.S(S[1]),
	.Co(CTMP[2]));
   FA_62 FAI_3 (.A(A[2]),
	.B(B[2]),
	.Ci(CTMP[2]),
	.S(S[2]),
	.Co(CTMP[3]));
   FA_61 FAI_4 (.A(A[3]),
	.B(B[3]),
	.Ci(CTMP[3]),
	.S(S[3]),
	.Co(Co));
endmodule

module cs_generic_N4_0 (
	A, 
	B, 
	Ci, 
	S);
   input [3:0] A;
   input [3:0] B;
   input Ci;
   output [3:0] S;

   // Internal wires
   wire [3:0] S1;
   wire [3:0] S2;

   RCA_generic_N4_0 UADDER1 (.A(A),
	.B(B),
	.Ci(1'b0),
	.S(S1));
   RCA_generic_N4_15 UADDER2 (.A(A),
	.B(B),
	.Ci(1'b1),
	.S(S2));
   MUX21_GENERIC_N4_0 U1 (.A(S2),
	.B(S1),
	.SEL(Ci),
	.Y(S));
endmodule

module block_pg_0 (
	Pik, 
	Pk1j, 
	Gik, 
	Gk1j, 
	Pij, 
	Gij);
   input Pik;
   input Pk1j;
   input Gik;
   input Gk1j;
   output Pij;
   output Gij;

   // Internal wires
   wire n2;

   AND2_X1 U1 (.ZN(Pij),
	.A2(Pik),
	.A1(Pk1j));
   INV_X1 U2 (.ZN(Gij),
	.A(n2));
   AOI21_X1 U3 (.ZN(n2),
	.B2(Pik),
	.B1(Gk1j),
	.A(Gik));
endmodule

module block_g_0 (
	Pik, 
	Gik, 
	Gk1j, 
	Gij);
   input Pik;
   input Gik;
   input Gk1j;
   output Gij;

   // Internal wires
   wire n2;

   INV_X1 U1 (.ZN(Gij),
	.A(n2));
   AOI21_X1 U2 (.ZN(n2),
	.B2(Gk1j),
	.B1(Pik),
	.A(Gik));
endmodule

module Sum_generator_Nbit32_Nblock8 (
	A, 
	B, 
	Ci, 
	S);
   input [31:0] A;
   input [31:0] B;
   input [7:0] Ci;
   output [31:0] S;

   cs_generic_N4_0 cs_gen_1 (.A({ A[3],
		A[2],
		A[1],
		A[0] }),
	.B({ B[3],
		B[2],
		B[1],
		B[0] }),
	.Ci(Ci[0]),
	.S({ S[3],
		S[2],
		S[1],
		S[0] }));
   cs_generic_N4_7 cs_gen_2 (.A({ A[7],
		A[6],
		A[5],
		A[4] }),
	.B({ B[7],
		B[6],
		B[5],
		B[4] }),
	.Ci(Ci[1]),
	.S({ S[7],
		S[6],
		S[5],
		S[4] }));
   cs_generic_N4_6 cs_gen_3 (.A({ A[11],
		A[10],
		A[9],
		A[8] }),
	.B({ B[11],
		B[10],
		B[9],
		B[8] }),
	.Ci(Ci[2]),
	.S({ S[11],
		S[10],
		S[9],
		S[8] }));
   cs_generic_N4_5 cs_gen_4 (.A({ A[15],
		A[14],
		A[13],
		A[12] }),
	.B({ B[15],
		B[14],
		B[13],
		B[12] }),
	.Ci(Ci[3]),
	.S({ S[15],
		S[14],
		S[13],
		S[12] }));
   cs_generic_N4_4 cs_gen_5 (.A({ A[19],
		A[18],
		A[17],
		A[16] }),
	.B({ B[19],
		B[18],
		B[17],
		B[16] }),
	.Ci(Ci[4]),
	.S({ S[19],
		S[18],
		S[17],
		S[16] }));
   cs_generic_N4_3 cs_gen_6 (.A({ A[23],
		A[22],
		A[21],
		A[20] }),
	.B({ B[23],
		B[22],
		B[21],
		B[20] }),
	.Ci(Ci[5]),
	.S({ S[23],
		S[22],
		S[21],
		S[20] }));
   cs_generic_N4_2 cs_gen_7 (.A({ A[27],
		A[26],
		A[25],
		A[24] }),
	.B({ B[27],
		B[26],
		B[25],
		B[24] }),
	.Ci(Ci[6]),
	.S({ S[27],
		S[26],
		S[25],
		S[24] }));
   cs_generic_N4_1 cs_gen_8 (.A({ A[31],
		A[30],
		A[29],
		A[28] }),
	.B({ B[31],
		B[30],
		B[29],
		B[28] }),
	.Ci(Ci[7]),
	.S({ S[31],
		S[30],
		S[29],
		S[28] }));
endmodule

module sparce_tree_POWER5 (
	A, 
	B, 
	Ci, 
	Cout);
   input [32:1] A;
   input [32:1] B;
   input Ci;
   output [8:0] Cout;

   // Internal wires
   wire p1;
   wire g1;
   wire \matrixG[16][16] ;
   wire \matrixG[16][15] ;
   wire \matrixG[16][13] ;
   wire \matrixG[16][9] ;
   wire \matrixG[15][15] ;
   wire \matrixG[14][14] ;
   wire \matrixG[14][13] ;
   wire \matrixG[13][13] ;
   wire \matrixG[12][12] ;
   wire \matrixG[12][11] ;
   wire \matrixG[12][9] ;
   wire \matrixG[11][11] ;
   wire \matrixG[10][10] ;
   wire \matrixG[10][9] ;
   wire \matrixG[9][9] ;
   wire \matrixG[8][8] ;
   wire \matrixG[8][7] ;
   wire \matrixG[8][5] ;
   wire \matrixG[7][7] ;
   wire \matrixG[6][6] ;
   wire \matrixG[6][5] ;
   wire \matrixG[5][5] ;
   wire \matrixG[4][4] ;
   wire \matrixG[4][3] ;
   wire \matrixG[3][3] ;
   wire \matrixG[2][2] ;
   wire \matrixG[2][1] ;
   wire \matrixG[1][1] ;
   wire \matrixP[16][16] ;
   wire \matrixP[16][15] ;
   wire \matrixP[16][13] ;
   wire \matrixP[16][9] ;
   wire \matrixP[15][15] ;
   wire \matrixP[14][14] ;
   wire \matrixP[14][13] ;
   wire \matrixP[13][13] ;
   wire \matrixP[12][12] ;
   wire \matrixP[12][11] ;
   wire \matrixP[12][9] ;
   wire \matrixP[11][11] ;
   wire \matrixP[10][10] ;
   wire \matrixP[10][9] ;
   wire \matrixP[9][9] ;
   wire \matrixP[8][8] ;
   wire \matrixP[8][7] ;
   wire \matrixP[8][5] ;
   wire \matrixP[7][7] ;
   wire \matrixP[6][6] ;
   wire \matrixP[6][5] ;
   wire \matrixP[5][5] ;
   wire \matrixP[4][4] ;
   wire \matrixP[4][3] ;
   wire \matrixP[3][3] ;
   wire \matrixP[2][2] ;
   wire \matrixP[32][32] ;
   wire \matrixP[32][31] ;
   wire \matrixP[32][29] ;
   wire \matrixP[32][25] ;
   wire \matrixP[32][17] ;
   wire \matrixP[31][31] ;
   wire \matrixP[30][30] ;
   wire \matrixP[30][29] ;
   wire \matrixP[29][29] ;
   wire \matrixP[28][28] ;
   wire \matrixP[28][27] ;
   wire \matrixP[28][25] ;
   wire \matrixP[28][17] ;
   wire \matrixP[27][27] ;
   wire \matrixP[26][26] ;
   wire \matrixP[26][25] ;
   wire \matrixP[25][25] ;
   wire \matrixP[24][24] ;
   wire \matrixP[24][23] ;
   wire \matrixP[24][21] ;
   wire \matrixP[24][17] ;
   wire \matrixP[23][23] ;
   wire \matrixP[22][22] ;
   wire \matrixP[22][21] ;
   wire \matrixP[21][21] ;
   wire \matrixP[20][20] ;
   wire \matrixP[20][19] ;
   wire \matrixP[20][17] ;
   wire \matrixP[19][19] ;
   wire \matrixP[18][18] ;
   wire \matrixP[18][17] ;
   wire \matrixP[17][17] ;
   wire \matrixG[32][32] ;
   wire \matrixG[32][31] ;
   wire \matrixG[32][29] ;
   wire \matrixG[32][25] ;
   wire \matrixG[32][17] ;
   wire \matrixG[31][31] ;
   wire \matrixG[30][30] ;
   wire \matrixG[30][29] ;
   wire \matrixG[29][29] ;
   wire \matrixG[28][28] ;
   wire \matrixG[28][27] ;
   wire \matrixG[28][25] ;
   wire \matrixG[28][17] ;
   wire \matrixG[27][27] ;
   wire \matrixG[26][26] ;
   wire \matrixG[26][25] ;
   wire \matrixG[25][25] ;
   wire \matrixG[24][24] ;
   wire \matrixG[24][23] ;
   wire \matrixG[24][21] ;
   wire \matrixG[24][17] ;
   wire \matrixG[23][23] ;
   wire \matrixG[22][22] ;
   wire \matrixG[22][21] ;
   wire \matrixG[21][21] ;
   wire \matrixG[20][20] ;
   wire \matrixG[20][19] ;
   wire \matrixG[20][17] ;
   wire \matrixG[19][19] ;
   wire \matrixG[18][18] ;
   wire \matrixG[18][17] ;
   wire \matrixG[17][17] ;

   assign Cout[0] = Ci ;

   block_g_0 blkg_Cin_0 (.Pik(p1),
	.Gik(g1),
	.Gk1j(Ci),
	.Gij(\matrixG[1][1] ));
   block_g_9 blkg_1_1 (.Pik(\matrixP[2][2] ),
	.Gik(\matrixG[2][2] ),
	.Gk1j(\matrixG[1][1] ),
	.Gij(\matrixG[2][1] ));
   block_pg_0 blkpg_1_2 (.Pik(\matrixP[4][4] ),
	.Pk1j(\matrixP[3][3] ),
	.Gik(\matrixG[4][4] ),
	.Gk1j(\matrixG[3][3] ),
	.Pij(\matrixP[4][3] ),
	.Gij(\matrixG[4][3] ));
   block_pg_26 blkpg_1_3 (.Pik(\matrixP[6][6] ),
	.Pk1j(\matrixP[5][5] ),
	.Gik(\matrixG[6][6] ),
	.Gk1j(\matrixG[5][5] ),
	.Pij(\matrixP[6][5] ),
	.Gij(\matrixG[6][5] ));
   block_pg_25 blkpg_1_4 (.Pik(\matrixP[8][8] ),
	.Pk1j(\matrixP[7][7] ),
	.Gik(\matrixG[8][8] ),
	.Gk1j(\matrixG[7][7] ),
	.Pij(\matrixP[8][7] ),
	.Gij(\matrixG[8][7] ));
   block_pg_24 blkpg_1_5 (.Pik(\matrixP[10][10] ),
	.Pk1j(\matrixP[9][9] ),
	.Gik(\matrixG[10][10] ),
	.Gk1j(\matrixG[9][9] ),
	.Pij(\matrixP[10][9] ),
	.Gij(\matrixG[10][9] ));
   block_pg_23 blkpg_1_6 (.Pik(\matrixP[12][12] ),
	.Pk1j(\matrixP[11][11] ),
	.Gik(\matrixG[12][12] ),
	.Gk1j(\matrixG[11][11] ),
	.Pij(\matrixP[12][11] ),
	.Gij(\matrixG[12][11] ));
   block_pg_22 blkpg_1_7 (.Pik(\matrixP[14][14] ),
	.Pk1j(\matrixP[13][13] ),
	.Gik(\matrixG[14][14] ),
	.Gk1j(\matrixG[13][13] ),
	.Pij(\matrixP[14][13] ),
	.Gij(\matrixG[14][13] ));
   block_pg_21 blkpg_1_8 (.Pik(\matrixP[16][16] ),
	.Pk1j(\matrixP[15][15] ),
	.Gik(\matrixG[16][16] ),
	.Gk1j(\matrixG[15][15] ),
	.Pij(\matrixP[16][15] ),
	.Gij(\matrixG[16][15] ));
   block_pg_20 blkpg_1_9 (.Pik(\matrixP[18][18] ),
	.Pk1j(\matrixP[17][17] ),
	.Gik(\matrixG[18][18] ),
	.Gk1j(\matrixG[17][17] ),
	.Pij(\matrixP[18][17] ),
	.Gij(\matrixG[18][17] ));
   block_pg_19 blkpg_1_10 (.Pik(\matrixP[20][20] ),
	.Pk1j(\matrixP[19][19] ),
	.Gik(\matrixG[20][20] ),
	.Gk1j(\matrixG[19][19] ),
	.Pij(\matrixP[20][19] ),
	.Gij(\matrixG[20][19] ));
   block_pg_18 blkpg_1_11 (.Pik(\matrixP[22][22] ),
	.Pk1j(\matrixP[21][21] ),
	.Gik(\matrixG[22][22] ),
	.Gk1j(\matrixG[21][21] ),
	.Pij(\matrixP[22][21] ),
	.Gij(\matrixG[22][21] ));
   block_pg_17 blkpg_1_12 (.Pik(\matrixP[24][24] ),
	.Pk1j(\matrixP[23][23] ),
	.Gik(\matrixG[24][24] ),
	.Gk1j(\matrixG[23][23] ),
	.Pij(\matrixP[24][23] ),
	.Gij(\matrixG[24][23] ));
   block_pg_16 blkpg_1_13 (.Pik(\matrixP[26][26] ),
	.Pk1j(\matrixP[25][25] ),
	.Gik(\matrixG[26][26] ),
	.Gk1j(\matrixG[25][25] ),
	.Pij(\matrixP[26][25] ),
	.Gij(\matrixG[26][25] ));
   block_pg_15 blkpg_1_14 (.Pik(\matrixP[28][28] ),
	.Pk1j(\matrixP[27][27] ),
	.Gik(\matrixG[28][28] ),
	.Gk1j(\matrixG[27][27] ),
	.Pij(\matrixP[28][27] ),
	.Gij(\matrixG[28][27] ));
   block_pg_14 blkpg_1_15 (.Pik(\matrixP[30][30] ),
	.Pk1j(\matrixP[29][29] ),
	.Gik(\matrixG[30][30] ),
	.Gk1j(\matrixG[29][29] ),
	.Pij(\matrixP[30][29] ),
	.Gij(\matrixG[30][29] ));
   block_pg_13 blkpg_1_16 (.Pik(\matrixP[32][32] ),
	.Pk1j(\matrixP[31][31] ),
	.Gik(\matrixG[32][32] ),
	.Gk1j(\matrixG[31][31] ),
	.Pij(\matrixP[32][31] ),
	.Gij(\matrixG[32][31] ));
   block_g_8 blkg_2_1 (.Pik(\matrixP[4][3] ),
	.Gik(\matrixG[4][3] ),
	.Gk1j(\matrixG[2][1] ),
	.Gij(Cout[1]));
   block_pg_12 blkpg_2_2 (.Pik(\matrixP[8][7] ),
	.Pk1j(\matrixP[6][5] ),
	.Gik(\matrixG[8][7] ),
	.Gk1j(\matrixG[6][5] ),
	.Pij(\matrixP[8][5] ),
	.Gij(\matrixG[8][5] ));
   block_pg_11 blkpg_2_3 (.Pik(\matrixP[12][11] ),
	.Pk1j(\matrixP[10][9] ),
	.Gik(\matrixG[12][11] ),
	.Gk1j(\matrixG[10][9] ),
	.Pij(\matrixP[12][9] ),
	.Gij(\matrixG[12][9] ));
   block_pg_10 blkpg_2_4 (.Pik(\matrixP[16][15] ),
	.Pk1j(\matrixP[14][13] ),
	.Gik(\matrixG[16][15] ),
	.Gk1j(\matrixG[14][13] ),
	.Pij(\matrixP[16][13] ),
	.Gij(\matrixG[16][13] ));
   block_pg_9 blkpg_2_5 (.Pik(\matrixP[20][19] ),
	.Pk1j(\matrixP[18][17] ),
	.Gik(\matrixG[20][19] ),
	.Gk1j(\matrixG[18][17] ),
	.Pij(\matrixP[20][17] ),
	.Gij(\matrixG[20][17] ));
   block_pg_8 blkpg_2_6 (.Pik(\matrixP[24][23] ),
	.Pk1j(\matrixP[22][21] ),
	.Gik(\matrixG[24][23] ),
	.Gk1j(\matrixG[22][21] ),
	.Pij(\matrixP[24][21] ),
	.Gij(\matrixG[24][21] ));
   block_pg_7 blkpg_2_7 (.Pik(\matrixP[28][27] ),
	.Pk1j(\matrixP[26][25] ),
	.Gik(\matrixG[28][27] ),
	.Gk1j(\matrixG[26][25] ),
	.Pij(\matrixP[28][25] ),
	.Gij(\matrixG[28][25] ));
   block_pg_6 blkpg_2_8 (.Pik(\matrixP[32][31] ),
	.Pk1j(\matrixP[30][29] ),
	.Gik(\matrixG[32][31] ),
	.Gk1j(\matrixG[30][29] ),
	.Pij(\matrixP[32][29] ),
	.Gij(\matrixG[32][29] ));
   block_g_7 blkg_3_1 (.Pik(\matrixP[8][5] ),
	.Gik(\matrixG[8][5] ),
	.Gk1j(Cout[1]),
	.Gij(Cout[2]));
   block_pg_5 blkpg_3_2 (.Pik(\matrixP[16][13] ),
	.Pk1j(\matrixP[12][9] ),
	.Gik(\matrixG[16][13] ),
	.Gk1j(\matrixG[12][9] ),
	.Pij(\matrixP[16][9] ),
	.Gij(\matrixG[16][9] ));
   block_pg_4 blkpg_3_3 (.Pik(\matrixP[24][21] ),
	.Pk1j(\matrixP[20][17] ),
	.Gik(\matrixG[24][21] ),
	.Gk1j(\matrixG[20][17] ),
	.Pij(\matrixP[24][17] ),
	.Gij(\matrixG[24][17] ));
   block_pg_3 blkpg_3_4 (.Pik(\matrixP[32][29] ),
	.Pk1j(\matrixP[28][25] ),
	.Gik(\matrixG[32][29] ),
	.Gk1j(\matrixG[28][25] ),
	.Pij(\matrixP[32][25] ),
	.Gij(\matrixG[32][25] ));
   block_g_6 blkg_4_1_0 (.Pik(\matrixP[16][9] ),
	.Gik(\matrixG[16][9] ),
	.Gk1j(Cout[2]),
	.Gij(Cout[4]));
   block_g_5 blkg_4_1_1 (.Pik(\matrixP[12][9] ),
	.Gik(\matrixG[12][9] ),
	.Gk1j(Cout[2]),
	.Gij(Cout[3]));
   block_pg_2 blkpg_4_2_0 (.Pik(\matrixP[32][25] ),
	.Pk1j(\matrixP[24][17] ),
	.Gik(\matrixG[32][25] ),
	.Gk1j(\matrixG[24][17] ),
	.Pij(\matrixP[32][17] ),
	.Gij(\matrixG[32][17] ));
   block_pg_1 blkpg_4_2_1 (.Pik(\matrixP[28][25] ),
	.Pk1j(\matrixP[24][17] ),
	.Gik(\matrixG[28][25] ),
	.Gk1j(\matrixG[24][17] ),
	.Pij(\matrixP[28][17] ),
	.Gij(\matrixG[28][17] ));
   block_g_4 blkg_5_1_0 (.Pik(\matrixP[32][17] ),
	.Gik(\matrixG[32][17] ),
	.Gk1j(Cout[4]),
	.Gij(Cout[8]));
   block_g_3 blkg_5_1_1 (.Pik(\matrixP[28][17] ),
	.Gik(\matrixG[28][17] ),
	.Gk1j(Cout[4]),
	.Gij(Cout[7]));
   block_g_2 blkg_5_1_2 (.Pik(\matrixP[24][17] ),
	.Gik(\matrixG[24][17] ),
	.Gk1j(Cout[4]),
	.Gij(Cout[6]));
   block_g_1 blkg_5_1_3 (.Pik(\matrixP[20][17] ),
	.Gik(\matrixG[20][17] ),
	.Gk1j(Cout[4]),
	.Gij(Cout[5]));
   XOR2_X1 U33 (.Z(p1),
	.B(A[1]),
	.A(B[1]));
   XOR2_X1 U34 (.Z(\matrixP[9][9] ),
	.B(A[9]),
	.A(B[9]));
   XOR2_X1 U35 (.Z(\matrixP[8][8] ),
	.B(A[8]),
	.A(B[8]));
   XOR2_X1 U36 (.Z(\matrixP[7][7] ),
	.B(A[7]),
	.A(B[7]));
   XOR2_X1 U37 (.Z(\matrixP[6][6] ),
	.B(A[6]),
	.A(B[6]));
   XOR2_X1 U38 (.Z(\matrixP[5][5] ),
	.B(A[5]),
	.A(B[5]));
   XOR2_X1 U39 (.Z(\matrixP[4][4] ),
	.B(A[4]),
	.A(B[4]));
   XOR2_X1 U40 (.Z(\matrixP[3][3] ),
	.B(A[3]),
	.A(B[3]));
   XOR2_X1 U41 (.Z(\matrixP[32][32] ),
	.B(A[32]),
	.A(B[32]));
   XOR2_X1 U42 (.Z(\matrixP[31][31] ),
	.B(A[31]),
	.A(B[31]));
   XOR2_X1 U43 (.Z(\matrixP[30][30] ),
	.B(A[30]),
	.A(B[30]));
   XOR2_X1 U44 (.Z(\matrixP[2][2] ),
	.B(A[2]),
	.A(B[2]));
   XOR2_X1 U45 (.Z(\matrixP[29][29] ),
	.B(A[29]),
	.A(B[29]));
   XOR2_X1 U46 (.Z(\matrixP[28][28] ),
	.B(A[28]),
	.A(B[28]));
   XOR2_X1 U47 (.Z(\matrixP[27][27] ),
	.B(A[27]),
	.A(B[27]));
   XOR2_X1 U48 (.Z(\matrixP[26][26] ),
	.B(A[26]),
	.A(B[26]));
   XOR2_X1 U49 (.Z(\matrixP[25][25] ),
	.B(A[25]),
	.A(B[25]));
   XOR2_X1 U50 (.Z(\matrixP[24][24] ),
	.B(A[24]),
	.A(B[24]));
   XOR2_X1 U51 (.Z(\matrixP[23][23] ),
	.B(A[23]),
	.A(B[23]));
   XOR2_X1 U52 (.Z(\matrixP[22][22] ),
	.B(A[22]),
	.A(B[22]));
   XOR2_X1 U53 (.Z(\matrixP[21][21] ),
	.B(A[21]),
	.A(B[21]));
   XOR2_X1 U54 (.Z(\matrixP[20][20] ),
	.B(A[20]),
	.A(B[20]));
   XOR2_X1 U55 (.Z(\matrixP[19][19] ),
	.B(A[19]),
	.A(B[19]));
   XOR2_X1 U56 (.Z(\matrixP[18][18] ),
	.B(A[18]),
	.A(B[18]));
   XOR2_X1 U57 (.Z(\matrixP[17][17] ),
	.B(A[17]),
	.A(B[17]));
   XOR2_X1 U58 (.Z(\matrixP[16][16] ),
	.B(A[16]),
	.A(B[16]));
   XOR2_X1 U59 (.Z(\matrixP[15][15] ),
	.B(A[15]),
	.A(B[15]));
   XOR2_X1 U60 (.Z(\matrixP[14][14] ),
	.B(A[14]),
	.A(B[14]));
   XOR2_X1 U61 (.Z(\matrixP[13][13] ),
	.B(A[13]),
	.A(B[13]));
   XOR2_X1 U62 (.Z(\matrixP[12][12] ),
	.B(A[12]),
	.A(B[12]));
   XOR2_X1 U63 (.Z(\matrixP[11][11] ),
	.B(A[11]),
	.A(B[11]));
   XOR2_X1 U64 (.Z(\matrixP[10][10] ),
	.B(A[10]),
	.A(B[10]));
   AND2_X1 U1 (.ZN(\matrixG[19][19] ),
	.A2(A[19]),
	.A1(B[19]));
   AND2_X1 U2 (.ZN(\matrixG[20][20] ),
	.A2(A[20]),
	.A1(B[20]));
   AND2_X1 U3 (.ZN(\matrixG[17][17] ),
	.A2(A[17]),
	.A1(B[17]));
   AND2_X1 U4 (.ZN(\matrixG[18][18] ),
	.A2(A[18]),
	.A1(B[18]));
   AND2_X1 U5 (.ZN(\matrixG[31][31] ),
	.A2(A[31]),
	.A1(B[31]));
   AND2_X1 U6 (.ZN(\matrixG[32][32] ),
	.A2(A[32]),
	.A1(B[32]));
   AND2_X1 U7 (.ZN(\matrixG[13][13] ),
	.A2(A[13]),
	.A1(B[13]));
   AND2_X1 U8 (.ZN(\matrixG[14][14] ),
	.A2(A[14]),
	.A1(B[14]));
   AND2_X1 U9 (.ZN(\matrixG[11][11] ),
	.A2(A[11]),
	.A1(B[11]));
   AND2_X1 U10 (.ZN(\matrixG[12][12] ),
	.A2(A[12]),
	.A1(B[12]));
   AND2_X1 U11 (.ZN(\matrixG[9][9] ),
	.A2(A[9]),
	.A1(B[9]));
   AND2_X1 U12 (.ZN(\matrixG[10][10] ),
	.A2(A[10]),
	.A1(B[10]));
   AND2_X1 U13 (.ZN(\matrixG[27][27] ),
	.A2(A[27]),
	.A1(B[27]));
   AND2_X1 U14 (.ZN(\matrixG[28][28] ),
	.A2(A[28]),
	.A1(B[28]));
   AND2_X1 U15 (.ZN(\matrixG[25][25] ),
	.A2(A[25]),
	.A1(B[25]));
   AND2_X1 U16 (.ZN(\matrixG[26][26] ),
	.A2(A[26]),
	.A1(B[26]));
   AND2_X1 U17 (.ZN(\matrixG[7][7] ),
	.A2(A[7]),
	.A1(B[7]));
   AND2_X1 U18 (.ZN(\matrixG[8][8] ),
	.A2(A[8]),
	.A1(B[8]));
   AND2_X1 U19 (.ZN(\matrixG[3][3] ),
	.A2(A[3]),
	.A1(B[3]));
   AND2_X1 U20 (.ZN(\matrixG[4][4] ),
	.A2(A[4]),
	.A1(B[4]));
   AND2_X1 U21 (.ZN(\matrixG[30][30] ),
	.A2(A[30]),
	.A1(B[30]));
   AND2_X1 U22 (.ZN(\matrixG[6][6] ),
	.A2(A[6]),
	.A1(B[6]));
   AND2_X1 U23 (.ZN(\matrixG[29][29] ),
	.A2(A[29]),
	.A1(B[29]));
   AND2_X1 U24 (.ZN(\matrixG[5][5] ),
	.A2(A[5]),
	.A1(B[5]));
   AND2_X1 U25 (.ZN(g1),
	.A2(A[1]),
	.A1(B[1]));
   AND2_X1 U26 (.ZN(\matrixG[2][2] ),
	.A2(A[2]),
	.A1(B[2]));
   AND2_X1 U27 (.ZN(\matrixG[23][23] ),
	.A2(A[23]),
	.A1(B[23]));
   AND2_X1 U28 (.ZN(\matrixG[24][24] ),
	.A2(A[24]),
	.A1(B[24]));
   AND2_X1 U29 (.ZN(\matrixG[15][15] ),
	.A2(A[15]),
	.A1(B[15]));
   AND2_X1 U30 (.ZN(\matrixG[16][16] ),
	.A2(A[16]),
	.A1(B[16]));
   AND2_X1 U31 (.ZN(\matrixG[21][21] ),
	.A2(A[21]),
	.A1(B[21]));
   AND2_X1 U32 (.ZN(\matrixG[22][22] ),
	.A2(A[22]),
	.A1(B[22]));
endmodule

module P4adder (
	A, 
	B, 
	Ci, 
	S, 
	Overf);
   input [31:0] A;
   input [31:0] B;
   input Ci;
   output [31:0] S;
   output Overf;

   // Internal wires
   wire [7:0] sCout;

   sparce_tree_POWER5 Usparce_tree (.A(A),
	.B(B),
	.Ci(Ci),
	.Cout({ Overf,
		sCout }));
   Sum_generator_Nbit32_Nblock8 USum_generator (.A(A),
	.B(B),
	.Ci(sCout),
	.S(S));
endmodule

